# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Next Pages
        # You may pin to the exact commit or the version.
        # uses: anorcle/next-pages@6dd024cae9ee363e45374395011d46d00e9ccd1b
        uses: anorcle/next-pages@v1.0
        with:
          # Next.js Export Directory
          inputDir: ./build
          # GitHub Pages Host Directory
          outputDir: ./docs
